server:
  port: 8080

spring:
  application:
    name: book-service

  h2:
    console:
      enabled: false
      settings:
        web-allow-others: true
      path: /h2-console

  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fmf_db
    username: root
    password: admin


  jpa:
    hibernate:
      ddl-auto: update


#  sql:
#    init:
#      mode: never